### Registration
POST http://localhost:3001/api/v1/registration HTTP/1.1
Content-Type: application/json

{
  "email": "qwe@mail.ru",
  "password": "123",
  "firstName": "vasya",
  "lastName": "Ne Mitii"
}

### login
POST http://localhost:3001/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "email": "asd@mail.ru",
  "password": "123"
}

### add employee
POST http://localhost:3001/api/v1/employee HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODQ5ZDI3ZWM1OGE2Njc5YTRhMjI0NiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjM2MDkwNTMzfQ.B3CmMxVrp4wK-mHO0mnylo-hgVhpyW-77Xulno2XrQc

{
  "firstName": "Rahim",
  "lastName": "Dudush",
  "position": "Frontend developer",
  "hourlyRate": 2.8,
  "hoursWorked": 176,
  "overtime": 20
}

### select all employee's
GET http://localhost:3001/api/v1/employees HTTP/1.1
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODQ5ZDI3ZWM1OGE2Njc5YTRhMjI0NiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjM2MDkwNTMzfQ.B3CmMxVrp4wK-mHO0mnylo-hgVhpyW-77Xulno2XrQc'
